//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evotiva.Modules.DNNSearchAndReplace {
    
    
    public partial class Settings {
        
        /// <summary>
        /// plSelectedSearchTargets control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl plSelectedSearchTargets;
        
        /// <summary>
        /// lstSelectedSearchTargets control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.Web.UI.WebControls.DnnListBox lstSelectedSearchTargets;
        
        /// <summary>
        /// plAvailableSearchTargets control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl plAvailableSearchTargets;
        
        /// <summary>
        /// grdAvailableSearchTargets control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.Web.UI.WebControls.DnnGrid grdAvailableSearchTargets;
    }
}
